"""aggiunta_quotazioni_correnti

Revision ID: 26b51d1cd489
Revises: cada636d2b5e
Create Date: 2026-06-01 18:59:26.865418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b51d1cd489'
down_revision: Union[str, Sequence[str], None] = 'cada636d2b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotazioni_correnti',
    sa.Column('ticker', sa.String(length=15), nullable=False),
    sa.Column('prezzo_corrente', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('recuperata_il', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotazioni_correnti')
    # ### end Alembic commands ###
