"""creazione_schema_iniziale

Revision ID: cada636d2b5e
Revises: 
Create Date: 2026-05-31 21:25:40.206548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cada636d2b5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portafogli',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.String(length=500), nullable=True),
    sa.Column('creato_il', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importazioni',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portafoglio_id', sa.Integer(), nullable=False),
    sa.Column('nome_file_originale', sa.String(length=255), nullable=False),
    sa.Column('formato_file', sa.String(length=10), nullable=False),
    sa.Column('percorso_archiviazione', sa.String(length=500), nullable=True),
    sa.Column('stato', sa.String(length=20), server_default='in_attesa', nullable=False),
    sa.Column('righe_totali', sa.Integer(), server_default='0', nullable=False),
    sa.Column('righe_importate', sa.Integer(), server_default='0', nullable=False),
    sa.Column('creato_il', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("formato_file IN ('csv', 'json')", name='ck_importazioni_formato_file'),
    sa.CheckConstraint("stato IN ('in_attesa', 'completata', 'fallita')", name='ck_importazioni_stato'),
    sa.CheckConstraint('righe_importate >= 0', name='ck_importazioni_righe_importate_non_negative'),
    sa.CheckConstraint('righe_totali >= 0', name='ck_importazioni_righe_totali_non_negative'),
    sa.ForeignKeyConstraint(['portafoglio_id'], ['portafogli.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importazioni_portafoglio_id'), 'importazioni', ['portafoglio_id'], unique=False)
    op.create_table('titoli_posseduti',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portafoglio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=15), nullable=False),
    sa.Column('quantita', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('prezzo_medio_acquisto', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('data_acquisto', sa.Date(), nullable=False),
    sa.Column('settore', sa.String(length=100), nullable=False),
    sa.Column('mercato', sa.String(length=50), nullable=False),
    sa.Column('creato_il', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('prezzo_medio_acquisto >= 0', name='ck_titoli_posseduti_prezzo_non_negativo'),
    sa.CheckConstraint('quantita > 0', name='ck_titoli_posseduti_quantita_positiva'),
    sa.ForeignKeyConstraint(['portafoglio_id'], ['portafogli.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portafoglio_id', 'ticker', name='uq_titoli_posseduti_portafoglio_ticker')
    )
    op.create_index(op.f('ix_titoli_posseduti_portafoglio_id'), 'titoli_posseduti', ['portafoglio_id'], unique=False)
    op.create_table('errori_importazione',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('importazione_id', sa.Integer(), nullable=False),
    sa.Column('numero_riga', sa.Integer(), nullable=True),
    sa.Column('nome_campo', sa.String(length=100), nullable=True),
    sa.Column('messaggio', sa.String(length=500), nullable=False),
    sa.Column('dati_originali', sa.Text(), nullable=True),
    sa.Column('creato_il', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['importazione_id'], ['importazioni.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_errori_importazione_importazione_id'), 'errori_importazione', ['importazione_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_errori_importazione_importazione_id'), table_name='errori_importazione')
    op.drop_table('errori_importazione')
    op.drop_index(op.f('ix_titoli_posseduti_portafoglio_id'), table_name='titoli_posseduti')
    op.drop_table('titoli_posseduti')
    op.drop_index(op.f('ix_importazioni_portafoglio_id'), table_name='importazioni')
    op.drop_table('importazioni')
    op.drop_table('portafogli')
    # ### end Alembic commands ###
