"""rimozione_storico_importazioni

Revision ID: d9df7ad16c7f
Revises: 26b51d1cd489
Create Date: 2026-06-02 18:06:21.749870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9df7ad16c7f'
down_revision: Union[str, Sequence[str], None] = '26b51d1cd489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table("errori_importazione")
    op.drop_table("importazioni")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importazioni',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('portafoglio_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome_file_originale', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('formato_file', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('percorso_archiviazione', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('stato', mysql.VARCHAR(length=20), server_default=sa.text("'in_attesa'"), nullable=False),
    sa.Column('righe_totali', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('righe_importate', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('creato_il', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.CheckConstraint("(`formato_file` in (_utf8mb4'csv',_utf8mb4'json'))", name=op.f('ck_importazioni_formato_file')),
    sa.CheckConstraint("(`stato` in (_utf8mb4'in_attesa',_utf8mb4'completata',_utf8mb4'fallita'))", name=op.f('ck_importazioni_stato')),
    sa.CheckConstraint('(`righe_importate` >= 0)', name=op.f('ck_importazioni_righe_importate_non_negative')),
    sa.CheckConstraint('(`righe_totali` >= 0)', name=op.f('ck_importazioni_righe_totali_non_negative')),
    sa.ForeignKeyConstraint(['portafoglio_id'], ['portafogli.id'], name=op.f('importazioni_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_importazioni_portafoglio_id'), 'importazioni', ['portafoglio_id'], unique=False)
    op.create_table('errori_importazione',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('importazione_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero_riga', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome_campo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('messaggio', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('dati_originali', mysql.TEXT(), nullable=True),
    sa.Column('creato_il', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['importazione_id'], ['importazioni.id'], name=op.f('errori_importazione_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_errori_importazione_importazione_id'), 'errori_importazione', ['importazione_id'], unique=False)
    # ### end Alembic commands ###
